// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAs1wJeOxboziNhu0oGnS3AbknzG-Ke1gA',
    appId: '1:290333653941:web:53711f70ae258c4b35f7fc',
    messagingSenderId: '290333653941',
    projectId: 'cmsc-23-project-91380',
    authDomain: 'cmsc-23-project-91380.firebaseapp.com',
    storageBucket: 'cmsc-23-project-91380.appspot.com',
    measurementId: 'G-MXHHJ0VYSB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7NMVx2ikXGOUufvm1afNW-T-0NPtrCIk',
    appId: '1:290333653941:android:13a286896a779b1535f7fc',
    messagingSenderId: '290333653941',
    projectId: 'cmsc-23-project-91380',
    storageBucket: 'cmsc-23-project-91380.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAd9fnd0aDG1OgpA3skg0AD5eJ88D5TmK4',
    appId: '1:290333653941:ios:3733f599b7e37c7b35f7fc',
    messagingSenderId: '290333653941',
    projectId: 'cmsc-23-project-91380',
    storageBucket: 'cmsc-23-project-91380.appspot.com',
    iosClientId: '290333653941-q42c95c57tbr9kjn56ppsgrr6mkfprph.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAd9fnd0aDG1OgpA3skg0AD5eJ88D5TmK4',
    appId: '1:290333653941:ios:3733f599b7e37c7b35f7fc',
    messagingSenderId: '290333653941',
    projectId: 'cmsc-23-project-91380',
    storageBucket: 'cmsc-23-project-91380.appspot.com',
    iosClientId: '290333653941-q42c95c57tbr9kjn56ppsgrr6mkfprph.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectApp',
  );
}
